### ISSUE TITLE
Request for supporting create or update comment

### ISSUE THREAD

**Issue by gizumon** [kevincobain2000/action-coveritup#25]
### Request

It would be nice If you could support `create or update` comments.

### AsIs

```yml
    - name: Comment on PR if it is a pull req
      if: ${{inputs.pr_comment == 'true' && github.event_name == 'pull_request' && steps.branch-name.outputs.base_ref_branch != '' && env.PR_HTTP_RESPONSE == '201' && github.event.pull_request.head.repo.full_name == github.repository }}
      uses: peter-evans/create-or-update-comment@v3
      with:
        issue-number: ${{ steps.pr-number-id.outputs.pr }}
        body-path: comment_body.txt
        token: ${{ inputs.token }}
```

### ToBe

```yml
    # Create or update comment
    - name: Find Comment
      uses: peter-evans/find-comment@v2
      if: github.event_name == 'pull_request' && success() && inputs.pr_comment == 'true' && env.PR_HTTP_RESPONSE == '201'
      id: fc
      with:
        issue-number: ${{ github.event.number }}
        body-includes: '<!-- __SOME_ANCHOR__ -->' # some anchor in the comment body
        token: ${{ inputs.token }}

    - name: Create Comment
      uses: peter-evans/create-or-update-comment@v2
      if: github.event_name == 'pull_request' && success() && inputs.pr_comment == 'true' && steps.fc.outputs.comment-id == 0 && env.PR_HTTP_RESPONSE == '201'
      with:
        issue-number: ${{ github.event.number }}
        body: comment_body.txt
        token: ${{ inputs.token }}

    - name: Update Comment
      uses: peter-evans/create-or-update-comment@v2
      if: github.event_name == 'pull_request' && success() && inputs.pr_comment == 'true' && steps.fc.outputs.comment-id != 0 && env.PR_HTTP_RESPONSE == '201'
      with:
        issue-number: ${{ github.event.number }}
        body: comment_body.txt
        comment-id: ${{ steps.fc.outputs.comment-id }}
        token: ${{ inputs.token }}
        edit-mode: replace
```
